# Generated by Django 4.2.2 on 2023-06-23 02:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='departament',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='employee',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='section',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='update_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='title',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
