# Generated by Django 4.2.2 on 2023-06-23 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('maintenance', '0003_alter_maintenance_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='maintenance',
            old_name='title',
            new_name='company',
        ),
    ]
